apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
    name: rekrutteringsbistand-kandidat
    namespace: toi
    labels:
        team: toi
    annotations:
        nginx.ingress.kubernetes.io/proxy-read-timeout: '300'
spec:
    # prettier-ignore
    image: {{ image }}
    port: 8080
    liveness:
        path: /rekrutteringsbistand-kandidat/internal/isAlive
        initialDelay: 5
    readiness:
        path: /rekrutteringsbistand-kandidat/internal/isReady
        initialDelay: 5
    ingresses:
        - https://rekrutteringsbistand.dev.intern.nav.no/rekrutteringsbistand-kandidat
    env:
        - name: LAST_NED_CV_URL
          value: https://pam-personbruker-veileder.dev.intern.nav.no/cv/pdf?fnr=
        - name: ARBEIDSRETTET_OPPFOLGING_URL
          value: https://veilarbpersonflate.dev.intern.nav.no
