apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pam-kandidatsok-veileder
  namespace: {{{ namespace }}}
  labels:
    team: teampam
spec:
  image: {{{ image }}}
  port: 8080
  liveness:
    path: /pam-kandidatsok-veileder/internal/isAlive
    initialDelay: 60
    timeout: 1
    failureThreshold: 2
  readiness:
    path: /pam-kandidatsok-veileder/internal/isReady
    initialDelay: 60
    timeout: 1
  replicas:
    min: 1
    max: 2
  cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  vault:
    enabled: true
  prometheus:
    enabled: false
    path: /metrics
  ingresses:
    - {{{ ingress-veileder }}}
  env:
    - name: LOGINSERVICE_VEILEDER_URL
      value: {{{ loginservice-veileder }}}
    - name: LOGINSERVICE_LOGOUT_VEILEDER_URL
      value: {{{ logoutservice-veileder }}}
    - name: LAST_NED_CV_URL
      value: {{{ lastnedurl }}}
    - name: PAM_KANDIDATSOK_API_URL
      value: {{{ pamkandidatsokapi-veileder }}}
    - name: PAM_SEARCH_API_RESTSERVICE_URL
      value: {{{ pamsearchapi }}}
    - name: PAMPORTAL_URL
      value: {{{ pamportal }}}
